-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-07-21 11:05:14
-- Luau version 6, Types version 3
-- Time taken: 0.001097 seconds

return {
	[Enum.ConnectionError.DisconnectErrors] = {Enum.ConnectionError.DisconnectBadhash, Enum.ConnectionError.DisconnectBlockedIP, Enum.ConnectionError.DisconnectBySecurityPolicy, Enum.ConnectionError.DisconnectCloudEditKick, Enum.ConnectionError.DisconnectConnectionLost, Enum.ConnectionError.DisconnectDevMaintenance, Enum.ConnectionError.DisconnectDuplicatePlayer, Enum.ConnectionError.DisconnectDuplicateTicket, Enum.ConnectionError.DisconnectEvicted, Enum.ConnectionError.DisconnectHashTimeout, Enum.ConnectionError.DisconnectIdle, Enum.ConnectionError.DisconnectIllegalTeleport, Enum.ConnectionError.DisconnectNewSecurityKeyMismatch, Enum.ConnectionError.DisconnectOnRemoteSysStats, Enum.ConnectionError.DisconnectPlayerless, Enum.ConnectionError.DisconnectPrivateServerKickout, Enum.ConnectionError.DisconnectProtocolMismatch, Enum.ConnectionError.DisconnectRaknetErrors, Enum.ConnectionError.DisconnectReceivePacketError, Enum.ConnectionError.DisconnectReceivePacketStreamError, Enum.ConnectionError.DisconnectRejoin, Enum.ConnectionError.DisconnectRobloxMaintenance, Enum.ConnectionError.DisconnectSecurityKeyMismatch, Enum.ConnectionError.DisconnectSendPacketError, Enum.ConnectionError.DisconnectTimeout, Enum.ConnectionError.DisconnectWrongVersion};
	[Enum.ConnectionError.PlacelaunchErrors] = {Enum.ConnectionError.PlacelaunchCustomMessage, Enum.ConnectionError.PlacelaunchDisabled, Enum.ConnectionError.PlacelaunchError, Enum.ConnectionError.PlacelaunchFlooded, Enum.ConnectionError.PlacelaunchGameEnded, Enum.ConnectionError.PlacelaunchGameFull, Enum.ConnectionError.PlacelaunchHashException, Enum.ConnectionError.PlacelaunchHashExpired, Enum.ConnectionError.PlacelaunchHttpError, Enum.ConnectionError.PlacelaunchOtherError, Enum.ConnectionError.PlacelaunchPartyCannotFit, Enum.ConnectionError.PlacelaunchRestricted, Enum.ConnectionError.PlacelaunchUnauthorized, Enum.ConnectionError.PlacelaunchUserLeft, Enum.ConnectionError.PlacelaunchUserPrivacyUnauthorized};
	[Enum.ConnectionError.TeleportErrors] = {Enum.ConnectionError.TeleportFailure, Enum.ConnectionError.TeleportFlooded, Enum.ConnectionError.TeleportGameEnded, Enum.ConnectionError.TeleportGameFull, Enum.ConnectionError.TeleportGameNotFound, Enum.ConnectionError.TeleportIsTeleporting, Enum.ConnectionError.TeleportUnauthorized};
}